name: CI checks

on:
  push:
  #   branches:
  #     - "main"
  #     - "devel"
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: |
        cargo test --verbose
        cd src/toml_const_macros && cargo test --verbose

    - name: Run format check
      run: |
        cargo fmt --check
        cd src/toml_const_macros && cargo fmt --check

    - name: Run clippy
      run: |
        cargo clippy --all-targets --all-features
        cd src/toml_const_macros && cargo clippy --all-targets --all-features
