# taken from:
# https://pratikpc.medium.com/publishing-crates-using-github-actions-165ee67780e1
#
# publishes to crates.io every time a new git tag is created

on:
  push:
    # Pattern matched against refs/tags
    tags:
      # version tags
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run flag - clear this to publish'
        required: true
        default: '--dry-run'

name: Publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: |
          cargo publish --package toml_const_macros --token ${CRATES_IO_TOKEN} ${{inputs.dry_run}}
          cargo publish --package toml_const --token ${CRATES_IO_TOKEN} ${{inputs.dry_run}}

        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
